### ISSUE TITLE
Improve detection of supported standards

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#14]
See also https://stackoverflow.com/a/49367391/4069571
- The test should be done without a file
- The test should check a few known numbers (`89`, `03`, `11`, `14`, `17`, `20`)
- Numbers should be padded with zeros (currently `3` is checked, but `03` is not)

**Comment by GPMueller** [comment]
Implemented with b8e20fb0ac1fad23892de9e1d083f5ecaeb9fd03.

**Comment by GPMueller** [comment]
Unfortunately the suggested solution to not use a file does not work so trivially with Python2...

**Comment by NOhs** [comment]
Quoting from the `Readme` 

> One compiler (Clang), one build system (written in Python)

I don't read: "One build system that supports every Python version there is, because we have to capture every possible scenario"

Therefore, dropping Python2 support seems to be a valid option to me. On Windows, most ppl have Python3 anyways via Anaconda I would guess. On modern Linux, python3 can be easily installed via the respective package manager. On Mac OSX I would also assume that python3 can be easily installed with homebrew or so. Therefore, I do not think dropping Python2 support is so dramatic.

**Comment by GPMueller** [comment]
Only supporting Python3 from PR #23 onwards, where the proper detection of c++ dialects is implemented.

**Comment by GPMueller** [comment]
Merged with a7bbc88738d7863cfe6f0994f80914a99914d417.
