### ISSUE TITLE
Checking the readme.rst

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#28]
Since pypi is supposed to nicely render the *.rst file, we have to make sure it is bug-free. For this several tools can be put in the CI scripts, see also this discussion:
https://stackoverflow.com/questions/16367770/my-rst-readme-is-not-formatted-on-pypi-python-org

**Comment by NOhs** [comment]
Good to know. Thanks for the info.

**Comment by thautwarm** [comment]
@NOhs you're welcome, I'm looking forward to your stable release, that does help!

**Comment by thautwarm** [comment]
Note that you should use `twine` to upload the package:
```
python setup.py bdist_wheel &&
twine upload dist\*
```

**Comment by GPMueller** [comment]
A problem has appeared with the [deployment to PyPI](https://travis-ci.org/Trick-17/clang-build/jobs/609571455#L2095):
```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
PyPI upload failed.
```
It seems related to [this pypa issue](https://github.com/pypa/warehouse/issues/5890#issuecomment-494604077), where in our case the toml code blocks would be the problem. It is unclear to me how this should be resolved on our side, in particular since it previously worked (i.e. the toml code blocks were rendered correctly).

Installing `collective.checkdocs` on Travis and running `python3 setup.py checkdocs` would in this case tell us something like
```
<string>:194: (WARNING/2) Cannot analyze code. No Pygments lexer found for "toml".
error: long_description had reST syntax errors
```

**Comment by GPMueller** [comment]
Since b2750640b02b6b45c5e9a9ef2efd0fad162510cb we have a Readme.md instead. As there is a lot less potential for syntactic mistakes there and we will likely not add any test for it, I will close this issue.
