### ISSUE TITLE
Build Type

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#92]
So we have the option with clang-build to select the build type. But I don't think it has to be a target attribute. As the build type is kind of "global" per run as you do not compile a project in parts with debug and in parts with release options.

**Comment by GPMueller** [comment]
Agreed, this should simply be an environment option.

**Comment by GPMueller** [comment]
I just realised that this is already a property of the `Environment` class, and the same goes for `clang`, `clangpp` and `force_build`.

Also, instead of passing `files['headers']` etc. to the targets, we could simply pass the `files` dict (note the `HeaderOnly` targets currently don't get the `'sourcefiles'` part of the dict). These changes might shorten a lot of code.
